<?php

return [
    'permissions' => [
        'dashboard.view',
        'pasien.read',
        'pasien.write',
        'kunjungan.read',
        'kunjungan.write',
        'kunjungan.read_cross_poli',
        'rekam_medis.read',
        'rekam_medis.write',
        'rekam_medis.read_cross_poli',
        'master.manage',
        'user_access.manage',
        'role_poli.manage',
        'master_icd.manage',
        'obat_sync.manage',
        'settings.manage',
        'audit_log.read',
    ],
    'roles' => [
        'superadmin' => [
            'dashboard.view',
            'pasien.read',
            'pasien.write',
            'kunjungan.read',
            'kunjungan.write',
            'kunjungan.read_cross_poli',
            'rekam_medis.read',
            'rekam_medis.write',
            'rekam_medis.read_cross_poli',
            'master.manage',
            'user_access.manage',
            'role_poli.manage',
            'master_icd.manage',
            'obat_sync.manage',
            'settings.manage',
            'audit_log.read',
        ],
        'admin_poli' => [
            'dashboard.view',
            'pasien.read',
            'pasien.write',
            'kunjungan.read',
            'kunjungan.write',
        ],
        'dokter' => [
            'dashboard.view',
            'pasien.read',
            'kunjungan.read',
            'rekam_medis.read',
            'rekam_medis.write',
        ],
    ],
];
