// Generated by `bun init`

interface ImportMetaEnv {
    readonly VITE_API_BASE_URL?: string
    /** Diset `true` saat `bun run build` (lihat build.ts). */
    readonly PROD?: boolean
    readonly DEV?: boolean
}

interface ImportMeta {
    readonly env: ImportMetaEnv
}

declare module "*.svg" {
  /**
   * A path to the SVG file
   */
  const path: `${string}.svg`;
  export = path;
}

declare module "*.module.css" {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: { readonly [key: string]: string };
  export = classes;
}
